### ISSUE TITLE
The lxqt-menu-data-config-version.cmake file is not archicture neutral. 

### ISSUE THREAD

**Issue by darkshram** [lxqt/lxqt-menu-data#19]
Note: This is irrelevant for Linux distributions as Arch Linux or Gentoo Linux, but is relevant for distributions like Fedora and derivatives.

The installed file:

```
/usr/share/cmake/lxqt-menu-data/lxqt-menu-data-config-version.cmake
```

Has: 

```
  set(PACKAGE_VERSION "${PACKAGE_VERSION} (${installedBits}bit)")
```
Therefore,  cmake will include the CPU architecture used to build the package.

Discovered this while building RPM packages as *.noarch.rpm (because there are no binaries and files are installed into `/usr/share`, which is meant to be used **only for architecture independent data**) in my 64bit branch and then re-use the resulting *.noarch.rpm packages to build LXQt packages for my 32bits branch.

```
+ /usr/bin/cmake -S . -B i686-redhat-linux-gnu -Wno-dev -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_C_COMPILER:STRING=clang -DCMAKE_CXX_COMPILER:STRING=clang++ -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DBUILD_SHARED_LIBS:BOOL=ON -Wno-dev -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is Clang 14.0.5
-- The CXX compiler identification is Clang 14.0.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/ccache/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/ccache/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.72.4
-- Checking for module 'gio-unix-2.0'
--   Found gio-unix-2.0, version 2.72.4
-- Found GLIB: /usr/include/glib-2.0;/usr/lib/glib-2.0/include (found suitable version "2.72.4", minimum required is "2.50.0")
-- Checking for module 'libmenu-cache'
--   Found libmenu-cache, version 1.1.0
-- Found MenuCache: /usr/lib/libmenu-cache.so;/usr/lib/libglib-2.0.so (found suitable version "1.1.0", minimum required is "1.1.0")
CMake Error at CMakeLists.txt:42 (find_package):
  Could not find a configuration file for package "lxqt-menu-data" that is
  compatible with requested version "1.4.0".
  The following configuration files were considered but not accepted:
    /usr/share/cmake/lxqt-menu-data/lxqt-menu-data-config.cmake, version: 1.4.0 (64bit)
```

As POSIX standard, `/usr/share` should include only architecture independent files.

This means, at least `lxqt-menu-data-config-version.cmake` should be installed into `/usr/lib/cmake` or `/usr/lib64/cmake` instead of `/usr/share/cmake`, or to remove `(${installedBits}bit)` because it will include the CPU architecture used to build the package and therefore cannot be used to build packages for other CPU architectures.

So, my workaround was to build packages as *.i686.rpm and *.x86_64.rpm instead of *.noarch.rpm to avoid this issue.

**Comment by yan12125** [comment]
This is fixed in https://github.com/lxqt/lxqt-menu-data/pull/18 but not released yet.

@tsujan maybe releasing 1.4.1 with this fix is desired.

**Comment by tsujan** [comment]
> maybe releasing 1.4.1 with this fix is desired.

Done.

Not having been added to the watchers of this repository, I received no email notification until you called me. Corrected that now.
