### ISSUE TITLE
Unneeded entries are shown

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-menu-data#2]
Moving from `lxde-applications.menu` to `lxqt-applications.menu` in pcmanfm-qt's context menu "Open with other applications" more useless entries are now shown.

Before only "Preferences" was useless here:

![screen_area_sab_21:32:04_](https://user-images.githubusercontent.com/10681413/233803602-ea48d614-7f15-48bf-9961-428546c56986.png)

Now we have more useless stuff:

![screen_area_dom_09:29:24_](https://user-images.githubusercontent.com/10681413/233826213-16e30bb9-2e2c-4e77-951a-6a7bd926093a.png)

##### Expected Behavior

Show only applications - not preferences, leave menu and else

##### Current Behavior

Replicates the main menu

##### Possible Solution

Provide a cleaned up `lxqt-applications-context.menu` or `lxqt-applications-only.menu` which will be used [here](https://github.com/lxqt/libfm-qt/blob/760c1fe441e4cc975b1506e6d9820500112373be/src/appmenuview.cpp#L43):

` menu_cache = menu_cache_lookup("applications-only.menu");`

![screen_area_sab_21:59:34_](https://user-images.githubusercontent.com/10681413/233804085-46b61f30-04e8-419e-b967-6b8ab3af8320.png)

##### Context

Migrations to lxqt-menu-data in libfm-qt (replace ´lxde-applications.menu´ for use with menu cache

**Comment by tsujan** [comment]
Are you sure that they aren't needed? We have `menu://applications/` too. (Sorry, I haven't had time to look into this yet.)

**Comment by stefonarch** [comment]
Looks ok atm but has to be investigated more.

![screen_area_dom_20:04:38_](https://user-images.githubusercontent.com/10681413/233857232-fffc1a92-b027-4c3f-ad06-9582af4c64eb.png)

**Comment by tsujan** [comment]
Thanks for checking! I've forgotten the details of its code and haven't reread it yet.
