### ISSUE TITLE
Use master branch

### ISSUE THREAD

**Issue by luis-pereira** [lxqt/lxqt-menu-data#9]
LXQt repositories use `master` as the default branch.
Github seems to have changed the default to `main`.
This repo uses `main` which is confusing.

##### Expected Behavior

Use master as the default branch

##### Current Behavior
Using `main` as the default branch.

Use master branch

##### Possible Solution

Rename it

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* liblxqt Version: 
* lxqt-build-tools Version: 
* Package version:

**Comment by stefonarch** [comment]
I did some trials on my fork, looks like it is easier done in "Settings" here.
While searching I stumbled upon https://www.git-tower.com/learn/git/faq/git-rename-master-to-main/  which explains the reason behind the switch to main. 

But I think with all the existing forks switching  all repos to "main" is not an option for us.

**Comment by tsujan** [comment]
> I stumbled upon https://www.git-tower.com/learn/git/faq/git-rename-master-to-main/ ....

It's an absurd example of wokeism, that's spread everywhere nowadays.

> But I think with all the existing forks switching all repos to "main" is not an option for us.

Correct. It should be main → master. Those who feel denigrated by seeing the word "master" might want to consult social counselors.

**Comment by stefonarch** [comment]
Renamed, this is needed https://github.com/lxqt/lxqt/pull/2427

**Comment by stefonarch** [comment]
I agree, maybe with the couple  master/slave it's not appropriate anymore, but how about the schoolmasters? Anyway, this is done.

**Comment by tsujan** [comment]
> but how about the schoolmasters?

They'll coin a term.

BTW, "main" makes sense only when there's a "minor", whose original meaning is "lesser, smaller". Someone may feel hurt.

**Comment by yan12125** [comment]
As a record, I updated weblate settings for this repo to use `master` branch.
